# Generated by Django 5.0.6 on 2024-05-21 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Board_News', '0002_category_post_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['id'], 'verbose_name': 'комментарий', 'verbose_name_plural': 'комментарии'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['post_created_at'], 'verbose_name': 'пост', 'verbose_name_plural': 'посты'},
        ),
    ]
